# 默认使用的模型提供商（可选）
# qwen2.5-72b-instruct qwq-32b QwQ-32B-AWQ  Qwen2.5-14B-Instruct-1M
default_provider: deepseek

providers:
  302:
    base_url: https://api.302.ai/v1/chat/completions
    model_name: gemini-2.0-pro-exp-02-05
    env_mapping:
      api_key: API_302_KEY
      base_url: API_302_BASE_URL
      model_name: API_302_MODEL

  deepseek:
    base_url: https://api.deepseek.com/v1
    model_name: deepseek-reasoner
    env_mapping:
      api_key: DEEP_SEEK_API_KEY
      base_url: DEEPSEEK_BASE_URL
      model_name: DEEPSEEK_MODEL

  aliyun:
    base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
    model_name: qwen-max
    env_mapping:
      api_key: DASHSCOPE_API_KEY
      base_url: ALIYUN_BASE_URL
      model_name: ALIYUN_MODEL

  nvidia:
    base_url: https://integrate.api.nvidia.com/v1
    model_name: deepseek-ai/deepseek-r1
    env_mapping:
      api_key: NVIDIA_API_KEY
      base_url: NVIDIA_BASE_URL
      model_name: NVIDIA_MODEL

  lmstudio:
    base_url: http://127.0.0.1:1234/v1
    model_name: qwq-32b@q8_0
    env_mapping:
      api_key: NVIDIA_API_KEY
      base_url: LMSTUDIO_BASE_URL
      model_name: LMSTUDIO_MODEL
  hunyuan:
    base_url: https://api.hunyuan.cloud.tencent.com/v1
    model_name: hunyuan-t1-latest
    env_mapping:
      api_key: HUNYUAN_API_KEY
      base_url: HUNYUAN_BASE_URL
      model_name: HUNYUAN_MODEL
  siliconflow:
    base_url: https://api.siliconflow.cn/v1/
    model_name: Qwen/Qwen2.5-Coder-32B-Instruct
    env_mapping:
      api_key: SILICONFLOW_API_KEY
      base_url: SILICONFLOW_BASE_URL
      model_name: SILICONFLOW_MODEL
  vllm:
    base_url: http://192.168.3.108:8080/v1/
    model_name: Qwen2.5-14B-Instruct-1M
    env_mapping:
      api_key: SILICONFLOW_API_KEY
      base_url: SILICONFLOW_BASE_URL
      model_name: SILICONFLOW_MODEL