providers:
  dashscope:
    model_name: "qwq-32b"
    api_key_env: "DASHSCOPE_API_KEY"
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  
  deepseek:
    model_name: "deepseek-reasoner"
    api_key_env: "DEEP_SEEK_API_KEY"
    base_url: "https://api.deepseek.com/v1"
  
  openai:
    model_name: "gpt-4"
    api_key_env: "OPENAI_API_KEY"
    base_url: "https://api.openai.com/v1"

default_provider: "dashscope"
